### ISSUE TITLE
数据同步

### ISSUE THREAD

**Issue by zouchengli** [bytedance/unpub#14]
如何把https://pub.flutter-io.cn/ 数据同步到私服？

**Comment by pd4d10** [comment]
开发中，v2 版本会支持

**Comment by zouchengli** [comment]
> 开发中，v2 版本会支持
> 
> 目前是 302 到了公有源

我看到了日志302信息。那也就是说目前只是当hosted私服用，不能从公有源缓存至私服对吧？那目前有什么临时方法解决该需求，你们这个v2版本大概什么时候能release呢？

**Comment by zouchengli** [comment]
> 开发中，v2 版本会支持
> 
> 目前是 302 到了公有源

这个公有源默认是哪个地址？国内的还是国外的？

**Comment by pd4d10** [comment]
`upstream` 参数可以配置

**Comment by zouchengli** [comment]
> `upstream` 参数可以配置

**Comment by zouchengli** [comment]
> > `upstream` 参数可以配置

unpub      | Unhandled exception:
unpub      | FormatException: Could not find an option named "upstream".
