### ISSUE TITLE
怎么能把上传插件时的google验证去掉？

### ISSUE THREAD

**Issue by magicmadegithub** [bytedance/unpub#15]
上传插件的时候不好翻墙，请问怎么能把google验证去掉？

**Comment by pd4d10** [comment]
这个是 pub 客户端的行为，可以去 https://github.com/dart-lang/pub 这里咨询一下

**Comment by NashLegend** [comment]
clone pub，修改代码，编译，替换……

**Comment by royoda** [comment]
怎么去掉google验证呢，找不到解决方法～哭了

**Comment by royoda** [comment]
解决上传时需要谷歌验证-参考：https://blog.csdn.net/ameryzhu/article/details/101688994

**Comment by pd4d10** [comment]
https://github.com/bytedance/unpub/issues/36 seems to be related to this issue. Moving discussions there for more context
