### ISSUE TITLE
MongoDB connection string with authentication doesn't work

### ISSUE THREAD

**Issue by sdebruyn** [bytedance/unpub#2]
I tried using this package and supplied a connection string that includes my username and password.

E.g.: `mongodb+srv://myusername:mypassword@hostname.azure.mongodb.net/test?retryWrites=true&w=majority`

I got an error saying that the port is not valid (where my password was interpreted as the port). How should I format my connection string and supply my credentials?

**Comment by pd4d10** [comment]
Seems related to https://github.com/mongo-dart/mongo_dart/issues/137
