### ISSUE TITLE
Security suggestions

### ISSUE THREAD

**Issue by ened** [bytedance/unpub#20]
What is the recommendation on securing a private pub server? Does pub support authentication via HTTP, for example? 

We are planning to run a protected server for all developers around the world but would like to restrict access using a token or username/password.

**Comment by dellgreen** [comment]
I think the limitation is currently in the pub client tool as there seems to be a lot of open tickets on their github for people requesting different ways to present authentication to a pub dev server.

dart-lang/pub#2201

**Comment by pd4d10** [comment]
The token authentication seems to have been landed. Closing this, and we can discuss it here: https://github.com/bytedance/unpub/issues/36
