### ISSUE TITLE
Upload package archives to s3 buckets

### ISSUE THREAD

**Issue by augustorsouza** [bytedance/unpub#22]
Lots of companies use aws and might benefit from being able to store the packages in a s3 bucket instead of using the unpub server local filesystem

**Comment by pd4d10** [comment]
Yeah, it's easy to implement it with the abstract class [packageStore](https://github.com/bytedance/unpub/blob/master/unpub/lib/src/package_store.dart).

The thing  I'm not sure about is that if there is a Dart SDK. If no probably you should implement it first on your own.

**Comment by pd4d10** [comment]
Thanks to @Clean-Cole , we have [unpub_aws](https://github.com/bytedance/unpub/blob/master/unpub_aws/README.md) as the first customized package store. Please give it a try if you are still facing this issue.

Closing. Feel free to reopen it if there are other problems
