### ISSUE TITLE
unpub --database mongodb://localhost:27017/dart_pub does'nt work

### ISSUE THREAD

**Issue by tbm98** [bytedance/unpub#34]
I've run `unpub --database mongodb://localhost:27017/dart_pub` but got a error
```
Unhandled exception:
MongoDB ConnectionException: Could not connect to localhost:27017
- SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 50298
#0      _ConnectionManager.open (package:mongo_dart/src/network/connection_manager.dart:93:9)
<asynchronous suspension>
#1      Db.open (package:mongo_dart/src/database/db.dart:442:7)
<asynchronous suspension>
#2      main (file:///Users/minhtran/.pub-cache/hosted/pub.dartlang.org/unpub-2.0.0/bin/unpub.dart:27:3)
<asynchronous suspension>
```

**Comment by tbm98** [comment]
I'm missing MongoDB. my bad.

**Comment by zeqinjie** [comment]
> I've run `unpub --database mongodb://localhost:27017/dart_pub` but got a error
> 
> ```
> Unhandled exception:
> MongoDB ConnectionException: Could not connect to localhost:27017
> - SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 50298
> #0      _ConnectionManager.open (package:mongo_dart/src/network/connection_manager.dart:93:9)
> <asynchronous suspension>
> #1      Db.open (package:mongo_dart/src/database/db.dart:442:7)
> <asynchronous suspension>
> #2      main (file:///Users/minhtran/.pub-cache/hosted/pub.dartlang.org/unpub-2.0.0/bin/unpub.dart:27:3)
> <asynchronous suspension>
> ```

hellow. me too, How did you solve this problem?

**Comment by tbm98** [comment]
I don't directly solved this problem. But let try install mongodb and start it first @zeqinjie

**Comment by zeqinjie** [comment]
@tbm98 yes, i had install mongodb, and success start .but in my macbook is work, but other macbook it was fail

**Comment by zeqinjie** [comment]
> @zeqinjie is other install mongodb ?. This package required local machine have mongodb

@tbm98  yes it had install, and start success

<img width="520" alt="image" src="https://user-images.githubusercontent.com/8444646/166958471-68050263-9c7b-412f-a760-101b1bc530c4.png">

**Comment by tbm98** [comment]
@zeqinjie check your mongodb connection https://www.google.com/search?q=test+connection+mongodb&oq=test+connection+mo&aqs=chrome.1.69i57j0i19l2j0i19i22i30l6.11723j1j4&client=ms-android-samsung-ss&sourceid=chrome-mobile&ie=UTF-8
