### ISSUE TITLE
How to publish package to private pub?

### ISSUE THREAD

**Issue by Pikaurd** [bytedance/unpub#4]
Thanks for your working.

I have tried `pub publish --server localhost:4000` but no lucky. Can you tell me how to do that?

**Comment by pd4d10** [comment]
Hi, @Pikaurd , seems the scheme (HTTP or HTTPS) is necessary.

```sh
pub publish --server http://localhost:4000
```

**Comment by pd4d10** [comment]
Hi, I'm going to close this issue. Feel free to reopen it if there are still problems
