### ISSUE TITLE
How to add uploaders to existing published packages

### ISSUE THREAD

**Issue by mmarazik** [bytedance/unpub#57]
I have a local unpub server setup with mongodb and managed to publish my packages to my local server. How can other developers on my team when required publish new versions of the same package without getting error that they are not an uploader for this package.

**Comment by talisk** [comment]
@mmarazik `dart pub uploader --package=<package_name> add <user@email.address>`

**Comment by leoshusar** [comment]
Just wanted to tell that `pub uploader` will be removed in some time (but not soon probably), see [this](https://github.com/dart-lang/pub/issues/3287) issue. They recommend to add UI management instead.
