### ISSUE TITLE
Failing to publish packages to local pub server with error: DetailedApiRequestError(status: 400, message: No error details. HTTP status was: 400.)

### ISSUE THREAD

**Issue by mmarazik** [bytedance/unpub#68]
I have a local pub server setup on our local LAN, using a self signed https certificate

When trying to publish, I tried the following

$unpub_auth login
(successful authorization)
$dart pub token add https://192.168.8.174:4000 (server with unpub)
$flutter pub publish --server https://192.168.8.174:4000 

I get the following error

DetailedApiRequestError(status: 400, message: No error details. HTTP status was: 400.)
pub finished with exit code 1

This is the output of my flutter doctor

[✓] Flutter (Channel stable, 2.10.5, on macOS 11.3.1 20E241 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 12.5)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

Any help is greatly appreciated

**Comment by MobiliteDev** [comment]
I have the same error, did you find any solution ?

**Comment by talisk** [comment]
Hi @mmarazik 
@MobiliteDev 's steps are right.  You should migrate the old token to the new destination by `unpub_auth get`.
You can learn more details from https://github.com/bytedance/unpub/blob/master/unpub_auth/README.md
