### ISSUE TITLE
API Key based access

### ISSUE THREAD

**Issue by MisterJimson** [bytedance/unpub#9]
For those of us who want the server to be publicly available, but restrict access to specific people, is there a way to make access API key based?

**Comment by dellgreen** [comment]
I think the limitation is currently in the pub client tool  as there seems to be a lot of open tickets on their github for people requesting different ways to present authentication to a pub dev server. 

https://github.com/dart-lang/pub/issues/2201

**Comment by pd4d10** [comment]
> the limitation is currently in the pub client tool

Yeah, and it seems to be supported now, see #36
