### ISSUE TITLE
Package not visible after succesful publishing

### ISSUE THREAD

**Issue by mishraaditya595** [bytedance/unpub#98]
I am running unpub on my localhost and I created a test package and published it. 
<img width="232" alt="Screenshot 2024-05-08 at 11 13 54" src="https://github.com/bytedance/unpub/assets/54946784/2313a851-3aff-4338-8ac3-09ee9251cc92">

But when I launch unpub in my browser, I get this error:
`GET /webapi/packages?size=10&page=0&q=h
Error thrown by handler.
{ok: 0.0, errmsg: Unsupported OP_QUERY command: count. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal, code: 352, codeName: UnsupportedOpQueryCommand}
package:shelf/shelf_io.dart 138:16  handleRequest
`

I am using mongodb-community@4.4

**Comment by chunghei0116** [comment]
Any update? facing the same problem

**Comment by Badr-Aldin-Almasri** [comment]
Because unpub is based on an older version of the mongo_dart package, you should downgrade your MongoDB server to version 5 or earlier. Hopefully, this package will receive an update soon

**Comment by mishraaditya595** [comment]
> Any update? facing the same problem

I tried a couple of things but was not quite worth the hassle. So, I gave up.
